framework:
    secret: '%env(APP_SECRET)%'
    default_locale: '%locale%'
    
    session:
        enabled: true
        handler_id: Symfony\Component\HttpFoundation\Session\Storage\Handler\PdoSessionHandler
        cookie_path: "/"
        cookie_secure: auto
        cookie_samesite: lax
    
    php_errors:
        log: true
    
    assets:
        packages:
            backgrounds:
                base_url: '%env(APP_URL)%'
