parameters:
    locale: 'en'
    mailFrom: '%env(MAILER_FROM)%'
    mailTo: '%env(MAILER_TO)%'
    # Make sure the upload and relative dbDir dir match.
    # dbDir is added to the returned filename of FileUploader to make uploading and managing files easier.
    uploadDirectory: '%kernel.project_dir%/public/uploads/'
    dbDirectory: '/uploads/'

services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false
    
    App\:
        resource: '../src/*'
        exclude: '../src/{DependencyInjection,Entity,Migrations,Tests,Kernel.php}'
    
    App\Controller\:
        resource: '../src/Controller'
        tags: ['controller.service_arguments']
    
    Symfony\Bridge\Doctrine\Security\RememberMe\DoctrineTokenProvider: ~
    
    App\Service\TokenGenerator: ~
    
    Symfony\Component\HttpFoundation\Session\Storage\Handler\PdoSessionHandler:
        arguments:
            - 'mysql:dbname=micro_posts; host=127.0.0.1; port=3306'
            - { db_table: sessions, db_username: root, db_password:  }
            - { lock_mode: 1 }
    
    App\DataFixtures\UserFixtures:
        arguments:
            $defaultLocale: '%kernel.default_locale%'
    
    App\EventListener\EntityListener:
        tags:
            - { name: doctrine.event_listener, event: prePersist }
            - { name: doctrine.event_listener, event: preUpdate }
            - { name: doctrine.event_listener, event: postLoad }
    
    #    App\EventSubscriber\UserRegisterSubscriber:
    #        arguments:
    #            $defaultLocale: '%kernel.default_locale%'
    #
    #    App\EventSubscriber\LocaleSubscriber:
    #        arguments:
    #            $defaultLocale: '%kernel.default_locale%'
    #        tags: [kernel.event_subscriber]
    
    App\Service\MailSender:
        arguments:
            $mailFrom: '%mailFrom%'
            $mailTo: '%mailTo%'
    
    App\Service\FileUploader:
        arguments:
            $uploadDirectory: '%uploadDirectory%'
            $dbDirectory: '%dbDirectory%'